In [2]:
from transformers import pipeline

summariser = pipeline("summarization")

No model was supplied, defaulted to t5-small and revision d769bba (https://huggingface.co/t5-small).
Using a pipeline without specifying a model name and revision in production is not recommended.
Downloading: 100%|██████████| 242M/242M [00:05<00:00, 45.8MB/s] 
All model checkpoint layers were used when initializing TFT5ForConditionalGeneration.

All the layers of TFT5ForConditionalGeneration were initialized from the model checkpoint at t5-small.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFT5ForConditionalGeneration for predictions without further training.
Downloading: 100%|██████████| 792k/792k [00:01<00:00, 507kB/s]  
Downloading: 100%|██████████| 1.39M/1.39M [00:01<00:00, 926kB/s] 
/home/mayank-soni/.pyenv/versions/3.8.12/envs/text_summary/lib/python3.8/site-packages/transformers/models/t5/tokenization_t5_fast.py:156: FutureWarning: This tokenizer was incorrectly instantiated with a model max length of 512 which will be cor

[{'summary_text': "i've been waiting for a HuggingFace course my whole life . the course is a great way to get to know me ."}]

In [5]:
article = '''SINGAPORE: Singapore's core inflation eased slightly to 5.1 per cent in October, driven by smaller increases in electricity and gas prices, retail, as well as other goods and service, official data showed on Wednesday (Nov 23).
This is lower than the 5.3 per cent reported in September. It is the first time core inflation has eased since February.
Core inflation excludes accommodation and private transport costs. 
The headline consumer price index, or overall inflation, was 6.7 per cent year-on-year in October, lower than the 7.5 per cent in the previous month as private transport inflation eased, alongside the moderation in core inflation
"Core Inflation is projected to stay elevated in the next few quarters before slowing more discernibly in H2 2023 as the current tightness in the domestic labour market eases and global inflation moderates," said the Monetary Authority of Singapore (MAS) and the Ministry of Trade and Industry (MTI). 
For 2022 as a whole, overall inflation is expected to average about 6 per cent and core inflation about 4 per cent. 
In their outlook, the authorities said the demand conditions in major economies have softened while supply chain frictions have continued to ease. 
"Prices of energy and food commodities have come off the peaks reached earlier in the year, but remain high given ongoing supply constraints."
Additionally, labour markets in major advanced economies are still tight, keeping wage pressures strong. Singapore’s imported inflation across a range of goods and services is expected to remain significant for some time.
On the domestic front, unit labour costs will increase further in the near term alongside robust wage growth. At the same time, the cost of utilities is likely to remain elevated, said MTI and MAS. 
Firms are expected to continue to pass through accumulated import, labour and other business costs to consumer prices amid resilient demand.
Car and accommodation cost increases are also anticipated to stay firm in the quarters ahead amid tight COE quotas for cars and strong demand for rental housing, respectively.
In 2023, taking into account all factors including the increase for the Goods and Services Tax, the authorities said Singapore's headline and core inflation are projected to average 5.5 per cent to 6.5 per cent and 3.5 per cent and 4.5 per cent respectively. 
"Excluding the transitory effects of the GST hike, headline and core inflation are expected to come in at 4.5 to 5.5 per cent and 2.5 to 3.5 per cent, respectively."
MAS and MTI added that there are upside risks to the inflation outlook, including from fresh shocks to global commodity prices and more persistent-than-expected external inflation.
'''

'SINGAPORE: Singapore\'s core inflation eased slightly to 5.1 per cent in October, driven by smaller increases in electricity and gas prices, retail, as well as other goods and service, official data showed on Wednesday (Nov 23).\nThis is lower than the 5.3 per cent reported in September. It is the first time core inflation has eased since February.\nCore inflation excludes accommodation and private transport costs. \nThe headline consumer price index, or overall inflation, was 6.7 per cent year-on-year in October, lower than the 7.5 per cent in the previous month as private transport inflation eased, alongside the moderation in core inflation\n"Core Inflation is projected to stay elevated in the next few quarters before slowing more discernibly in H2 2023 as the current tightness in the domestic labour market eases and global inflation moderates," said the Monetary Authority of Singapore (MAS) and the Ministry of Trade and Industry (MTI). \nFor 2022 as a whole, overall inflation is ex

In [8]:
article2 = '''
"SINGAPORE: For the seventh consecutive year, 98.4 per cent of Primary 6 students who sat for the Primary School Leaving Examination (PSLE) made it to secondary school. This is the second cohort of students under the new Achievement Level (AL) scoring system.
The PSLE results were released from 11am on Wednesday (Nov 23). 
A total of 37,095 Primary 6 students sat for the PSLE this year, with 98.4 per cent eligible to enter secondary school, said the Ministry of Education (MOE) and the Singapore Examinations and Assessment Board (SEAB) in a joint press release on Wednesday.
Students eligible for the Express course made up 68.4 per cent of the cohort, with 18.7 per cent for the Normal (Academic) course and 11.3 per cent for the Normal (Technical) course. 
Under the AL system, Primary 6 students will receive ALs of 1 to 8 for each of their four subjects, with 1 being the best score and 8, the lowest. Their overall score will be the sum of these ALs. Students with a PSLE score between 4 and 20 are eligible for the Express course. Students who receive a score of 21 or 22 are offered an option between the Express course and Normal (Academic) course, while those with scores of 23 or 24 are eligible for the Normal (Academic) course. 
Under the subject-based banding, students in Normal (Academic) and Normal (Technical) courses will also be able to take certain subjects at a more demanding level from Secondary 1 based on their AL scores for individual PSLE subjects.
This year, about 62 per cent of students who qualified for the Normal courses are assessed to be suitable to take a least one subject at a more demanding level as they progress to secondary school.
Candidates who did not qualify for entry to secondary school can choose to retake the PSLE next year, said MOE and SEAB, adding that they can also apply to Assumption Pathway School and Northlight School with a recommendation from their primary school principal.
Both schools offer customised programmes with a more "experiential and hands-on learning" approach.
SECONDARY 1 POSTING EXERCISE
The Secondary 1 (S1) option form to select secondary schools will be given to eligible students together with their PSLE results. 
A unique S1 personal identification number (S1 PIN) can be found on the top-right corner of the S1 option form. 
Students should use the S1 PIN to log in to the Secondary 1 Internet System (S1-IS). They can download a copy of the S1 option form and submit their school choices online. 
The S1-IS will be accessible from 11.30am on Nov 23 to 3pm on Nov 29 via MOE's S1 Posting website. 
"When choosing a secondary school that would be a good fit for the student's overall educational needs, strengths and interests, students and parents are encouraged to consider a holistic range of factors," said MOE and SEAB. 
"This includes the school's distinctive programmes, subject offerings, Co-Curricular Activities (CCAs), ethos, culture, location and support for Special Educational Needs, if required," they added. 
SECONDARY 1 POSTING RESULTS
The posting results will be released between Dec 21 and Dec 23. The posting results can be accessed through any of the following channels:
Short Message Service (SMS)
S1-IS using the student's birth certificate number/FIN and the S1 PIN
The student's primary school 
Students do not need to report to their posted secondary schools upon receiving their posting results. 
They should instead refer to their posted schools’ websites for more information such as the reporting details, booklist, and the purchase of books and uniforms.
Parents of the incoming cohort who are on Parents Gateway will also receive instructions from the posted schools from the afternoon the posting results are released.
If students are unable to report to their posted secondary school on the first day of school in Jan 2023 due to valid reasons, they should inform their posted secondary school directly after receiving their results to confirm that they are taking up the place.
More information on S1 Posting and S1-IS is available at MOE’s S1 Posting website. For enquiries, parents can also visit www.moe.gov.sg/contact."
'''

'\n"SINGAPORE: For the seventh consecutive year, 98.4 per cent of Primary 6 students who sat for the Primary School Leaving Examination (PSLE) made it to secondary school. This is the second cohort of students under the new Achievement Level (AL) scoring system.\nThe PSLE results were released from 11am on Wednesday (Nov 23). \nA total of 37,095 Primary 6 students sat for the PSLE this year, with 98.4 per cent eligible to enter secondary school, said the Ministry of Education (MOE) and the Singapore Examinations and Assessment Board (SEAB) in a joint press release on Wednesday.\nStudents eligible for the Express course made up 68.4 per cent of the cohort, with 18.7 per cent for the Normal (Academic) course and 11.3 per cent for the Normal (Technical) course. \nUnder the AL system, Primary 6 students will receive ALs of 1 to 8 for each of their four subjects, with 1 being the best score and 8, the lowest. Their overall score will be the sum of these ALs. Students with a PSLE score betwe

In [13]:
summariser(article)

[{'summary_text': 'the headline consumer price index, or overall inflation, was 6.7 per cent year-on-year in October . for 2022 as a whole, overall inflation is expected to average about 6 per cent . meanwhile, labour markets in major advanced economies are still tight .'}]

# Tokenizing

In [7]:
from transformers import AutoTokenizer

checkpoint = "facebook/bart-large-cnn"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

Downloading: 100%|██████████| 899k/899k [00:01<00:00, 587kB/s]  
Downloading: 100%|██████████| 456k/456k [00:01<00:00, 308kB/s]  
Downloading: 100%|██████████| 1.36M/1.36M [00:01<00:00, 753kB/s] 


PreTrainedTokenizerFast(name_or_path='facebook/bart-large-cnn', vocab_size=50265, model_max_len=1024, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>', 'sep_token': '</s>', 'pad_token': '<pad>', 'cls_token': '<s>', 'mask_token': AddedToken("<mask>", rstrip=False, lstrip=True, single_word=False, normalized=False)})

In [10]:
raw_inputs = [
    article,
    article2
]
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="tf")

{'input_ids': <tf.Tensor: shape=(2, 935), dtype=int32, numpy=
array([[    0,   104,  1862, ...,     1,     1,     1],
       [    0, 50118,   113, ...,    72, 50118,     2]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 935), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>}

# Model

In [12]:
from transformers import TFAutoModel

model = TFAutoModel.from_pretrained(checkpoint)

Downloading: 100%|██████████| 1.63G/1.63G [01:34<00:00, 17.3MB/s]  
2022-11-23 13:30:39.862238: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 205881344 exceeds 10% of free system memory.
2022-11-23 13:30:40.288416: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 205881344 exceeds 10% of free system memory.
2022-11-23 13:30:40.556317: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 205881344 exceeds 10% of free system memory.
2022-11-23 13:30:59.335430: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 205881344 exceeds 10% of free system memory.
2022-11-23 13:31:00.232896: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 205881344 exceeds 10% of free system memory.
All model checkpoint layers were used when initializing TFBartModel.

All the layers of TFBartModel were initialized from the model checkpoint at facebook/bart-large-cnn.
If your task is similar to the task the model of the che